# Generated by Django 2.2.12 on 2020-05-27 20:30

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='school',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='schools',
            field=djongo.models.fields.ListField(default=['מדעי המחשב', 'משפטים'], verbose_name=models.CharField(max_length=50)),
        ),
    ]
