# Generated by Django 2.2.12 on 2020-04-10 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='String',
        ),
    ]
