# Generated by Django 2.2.12 on 2020-05-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.CharField(default='Computer Science', max_length=30),
        ),
    ]
