# Generated by Django 2.2.12 on 2020-04-11 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='name',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
