# Generated by Django 2.2.12 on 2020-05-29 07:51

import api.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200527_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsAnsweredPerCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=30)),
                ('questionsAnsweredPerSubject', djongo.models.fields.ArrayField(model_container=api.models.QuestionsAnsweredPerSubject)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionsAnsweredPerSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=30)),
                ('answeredCorrect', djongo.models.fields.ArrayField(model_container=api.models.Question)),
                ('answeredWrong', djongo.models.fields.ArrayField(model_container=api.models.Question)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='student',
            name='questionsAnsweredPerCourse',
            field=djongo.models.fields.ArrayField(default=[], model_container=api.models.QuestionsAnsweredPerCourse),
        ),
    ]
