# Generated by Django 2.2.12 on 2020-05-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_course_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='school',
            field=models.CharField(default='מדעי המחשב', max_length=30),
        ),
    ]
