# Generated by Django 2.2.12 on 2020-05-30 12:48

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200529_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSubmitted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', djongo.models.fields.ListField(max_length=5, verbose_name=models.CharField(max_length=50))),
                ('correctAnswer', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('body', models.CharField(max_length=100)),
                ('selectedAnswers', djongo.models.fields.ListField(verbose_name=models.IntegerField())),
                ('subject', models.CharField(max_length=30)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
