# Generated by Django 2.2.12 on 2020-04-07 18:47

from django.db import migrations, models
import djongo.models.fields
import frontend.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frontend', '0002_auto_20200407_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subjects', djongo.models.fields.ArrayField(model_container=frontend.models.Subject, model_form_class=frontend.models.SubjectForm)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
